// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfluflqvhfbngeppbmuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbHVmbHF2aGZibmdlcHBibXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDUwMTAsImV4cCI6MjA3MjE4MTAxMH0.ex76VjbhsNFXu5vhrjhNZgeo24bqQcyBLlASSRXkLtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});